kind1 = BadgeKind.create!(name: 'music')
kind2 = BadgeKind.create!(name: 'forum')
kind3 = BadgeKind.create!(name: 'community')
kind4 = BadgeKind.create!(name: 'Membership Level')
kind5 = BadgeKind.create!(name: 'Leaderboard Points')
kind6 = BadgeKind.create!(name: 'Speciality')
# kind1 = BadgeKind.find_by_name('music')
# kind2 = BadgeKind.find_by_name('forum')
# kind3 = BadgeKind.find_by_name('community')
# kind4 = BadgeKind.find_by_name('Membership Level')

BadgeActionType.create!(points: 100, name: 'like', badge_kind_id: kind1.id)
BadgeActionType.create!(points: 100, name: 'rate', badge_kind_id: kind1.id)
BadgeActionType.create!(points: 100, name: 'comment', badge_kind_id: kind1.id)
BadgeActionType.create!(points: 100, name: 'share', badge_kind_id: kind1.id)
BadgeActionType.create!(points: 100, name: 'listen', badge_kind_id: kind1.id)
BadgeActionType.create!(points: 100, name: 'download', badge_kind_id: kind1.id)
BadgeActionType.create!(points: 100, name: 'follow', badge_kind_id: kind1.id)
BadgeActionType.create!(points: 100, name: 'role fan', badge_kind_id: kind1.id)
BadgeActionType.create!(points: 100, name: 'role artist', badge_kind_id: kind1.id)

BadgeActionType.create!(points: 100, name: 'follow', badge_kind_id: kind2.id)
BadgeActionType.create!(points: 100, name: 'like', badge_kind_id: kind2.id)
BadgeActionType.create!(points: 100, name: 'make post', badge_kind_id: kind2.id)
BadgeActionType.create!(points: 100, name: 'role fan', badge_kind_id: kind2.id)
BadgeActionType.create!(points: 100, name: 'role artist', badge_kind_id: kind2.id)

BadgeActionType.create!(points: 100, name: 'follow', badge_kind_id: kind3.id)
BadgeActionType.create!(points: 100, name: 'comment', badge_kind_id: kind3.id)
BadgeActionType.create!(points: 100, name: 'role fan', badge_kind_id: kind3.id)
BadgeActionType.create!(points: 100, name: 'role artist', badge_kind_id: kind3.id)

BadgeActionType.create!(count_to_achieve: 30, name: 'monthly', badge_kind_id: kind4.id)
BadgeActionType.create!(count_to_achieve: 365, name: '1 year', badge_kind_id: kind4.id)
BadgeActionType.create!(count_to_achieve: 365*2, name: '2 years', badge_kind_id: kind4.id)
BadgeActionType.create!(count_to_achieve: 365*3, name: '3 years', badge_kind_id: kind4.id)
