kind1 = BadgeKind.create!(name: 'music')
kind2 = BadgeKind.create!(name: 'forum')
kind3 = BadgeKind.create!(name: 'community')

BadgeActionType.create!(points: 100, name: 'like', badge_kind_id: kind1.id)
BadgeActionType.create!(points: 100, name: 'rate', badge_kind_id: kind1.id)
BadgeActionType.create!(points: 100, name: 'comment', badge_kind_id: kind1.id)
BadgeActionType.create!(points: 100, name: 'share', badge_kind_id: kind1.id)
BadgeActionType.create!(points: 100, name: 'listen', badge_kind_id: kind1.id)
BadgeActionType.create!(points: 100, name: 'download', badge_kind_id: kind1.id)
BadgeActionType.create!(points: 100, name: 'follow', badge_kind_id: kind1.id)
BadgeActionType.create!(points: 100, name: 'role fan', badge_kind_id: kind1.id)
BadgeActionType.create!(points: 100, name: 'role artist', badge_kind_id: kind1.id)

BadgeActionType.create!(points: 100, name: 'follow', badge_kind_id: kind2.id)
BadgeActionType.create!(points: 100, name: 'like', badge_kind_id: kind2.id)
BadgeActionType.create!(points: 100, name: 'make post', badge_kind_id: kind2.id)
BadgeActionType.create!(points: 100, name: 'role fan', badge_kind_id: kind2.id)
BadgeActionType.create!(points: 100, name: 'role artist', badge_kind_id: kind2.id)

BadgeActionType.create!(points: 100, name: 'follow', badge_kind_id: kind3.id)
BadgeActionType.create!(points: 100, name: 'comment', badge_kind_id: kind3.id)
BadgeActionType.create!(points: 100, name: 'role fan', badge_kind_id: kind3.id)
BadgeActionType.create!(points: 100, name: 'role artist', badge_kind_id: kind3.id)
