BadgeActionType.create!(name: 'like')
BadgeActionType.create!(name: 'rate track')
BadgeActionType.create!(name: 'comment')
BadgeActionType.create!(name: 'share')
BadgeActionType.create!(name: 'listen track')
BadgeActionType.create!(name: 'download')
BadgeActionType.create!(name: 'follow')
BadgeActionType.create!(name: 'member over time')
BadgeActionType.create!(name: 'role')
BadgeKind.create!(name: 'music')
BadgeKind.create!(name: 'forum')
BadgeKind.create!(name: 'community')